import Phaser from "phaser";
import { mobTextureKey, dustPuff } from "../render/artkit";

export type EntityKind = "self" | "player" | "enemy";

interface EntityViewOptions {
  x: number;
  y: number;
  name: string;
  /** Optional body color override (e.g. per mob family). */
  color?: number;
  /** Mob kind (enemies) — picks the authored silhouette texture. */
  mobKind?: string;
  /** Bosses render larger with a smouldering aura ring. */
  boss?: boolean;
  /** Called when the body is clicked (for tab-targeting). */
  onClick: () => void;
}

const BAR_WIDTH = 46;
const BAR_HEIGHT = 6;

/**
 * The visual for one networked entity: a cast shadow, an authored silhouette
 * sprite (generated by the art kit), a nameplate (+ optional title line), and
 * a health bar, grouped in a container so they move together. Animated —
 * breathing at rest, bobbing on the move, flashing on hits, crumpling on
 * death — but pure presentation: it never decides game outcomes, it only
 * renders authoritative server state. Click hit areas are unchanged from the
 * classic build (circle r16 for players / 22×2 square for mobs).
 */
export class EntityView {
  readonly container: Phaser.GameObjects.Container;
  readonly radius: number;

  private readonly scene: Phaser.Scene;
  private readonly body: Phaser.GameObjects.Image;
  private readonly shadow: Phaser.GameObjects.Image;
  private readonly aura?: Phaser.GameObjects.Image;
  private mount: Phaser.GameObjects.Image | undefined = undefined;
  private skullBadge: Phaser.GameObjects.Text | undefined = undefined;
  private readonly nameText: Phaser.GameObjects.Text;
  private titleText: Phaser.GameObjects.Text | undefined = undefined;
  private readonly hpBar: Phaser.GameObjects.Rectangle;
  private readonly kind: EntityKind;

  private alive = true;
  private bobPhase = Math.random() * Math.PI * 2;
  private lastX: number;
  private lastY: number;
  private moving = 0; // decays each frame; > 0 means "recently moved"
  private baseTex = "";

  constructor(scene: Phaser.Scene, kind: EntityKind, opts: EntityViewOptions) {
    this.scene = scene;
    this.kind = kind;
    this.radius = kind === "enemy" ? 22 : 16;
    this.lastX = opts.x;
    this.lastY = opts.y;

    // Cast shadow grounds every actor in the world.
    this.shadow = scene.add
      .image(0, this.radius * 0.72, "fx-shadow")
      .setDisplaySize(this.radius * 2.4, this.radius * 1.1)
      .setAlpha(0.8);

    // The authored silhouette. Enemies pick their family texture; players get
    // the armored hero (self = green, others = blue, battleground = team).
    const texKey =
      kind === "enemy" ? mobTextureKey(scene, opts.mobKind ?? "") : kind === "self" ? "char-self" : "char-player";
    this.baseTex = texKey;
    this.body = scene.add.image(0, -4, texKey);
    if (opts.boss) this.body.setScale(1.35);
    // Heroes read slightly larger than life (visual only — hit areas and the
    // server collision box are untouched).
    if (kind !== "enemy") this.body.setScale(1.18);
    // Non-family mobs (fallback texture) keep their data color as a tint hint.
    if (kind === "enemy" && opts.mobKind && !scene.textures.exists(`mob-${opts.mobKind}`) && opts.color) {
      this.body.setTint(opts.color);
    }

    // Boss aura: a slow-pulsing warm ring beneath the body.
    if (opts.boss) {
      this.aura = scene.add
        .image(0, 2, "fx-glow")
        .setScale(1.1)
        .setAlpha(0.4)
        .setBlendMode(Phaser.BlendModes.ADD);
      scene.tweens.add({
        targets: this.aura,
        alpha: 0.18,
        scale: 0.9,
        duration: 1200,
        yoyo: true,
        repeat: -1,
        ease: "Sine.easeInOut",
      });
    }

    // The local player should not be clickable as a target. Hit areas match
    // the classic shapes exactly so tab-targeting feels identical.
    if (kind !== "self") {
      if (kind === "enemy") {
        this.body.setInteractive(
          new Phaser.Geom.Rectangle(
            this.body.width / 2 - this.radius,
            this.body.height / 2 - this.radius,
            this.radius * 2,
            this.radius * 2,
          ),
          Phaser.Geom.Rectangle.Contains,
        );
      } else {
        this.body.setInteractive(
          new Phaser.Geom.Circle(this.body.width / 2, this.body.height / 2, this.radius),
          Phaser.Geom.Circle.Contains,
        );
      }
      this.body.input!.cursor = "pointer";
      this.body.on(
        "pointerdown",
        (_p: Phaser.Input.Pointer, _x: number, _y: number, e: Phaser.Types.Input.EventData) => {
          e.stopPropagation();
          opts.onClick();
        },
      );
    }

    const barY = -this.radius - 12;
    const hpBarBg = scene.add.rectangle(0, barY, BAR_WIDTH + 2, BAR_HEIGHT + 2, 0x0b0e14, 0.85).setOrigin(0.5);
    this.hpBar = scene.add
      .rectangle(-BAR_WIDTH / 2, barY, BAR_WIDTH, BAR_HEIGHT, 0x4ade80)
      .setOrigin(0, 0.5);

    this.nameText = scene.add
      .text(0, barY - 12, opts.name, {
        fontFamily: "system-ui, sans-serif",
        fontSize: "13px",
        color: kind === "enemy" ? "#f1b8b0" : "#e6edf5",
      })
      .setOrigin(0.5)
      .setStroke("#05070a", 3);

    const children: Phaser.GameObjects.GameObject[] = [this.shadow];
    if (this.aura) children.push(this.aura);
    children.push(hpBarBg, this.hpBar, this.nameText, this.body);
    this.container = scene.add.container(opts.x, opts.y, children).setDepth(10);

    // Idle life: players breathe; mobs sway with a slower, heavier rhythm
    // (bosses barely move — mass reads as menace).
    const baseScale = this.body.scale;
    scene.tweens.add({
      targets: this.body,
      scaleY: baseScale * (kind === "enemy" ? (opts.boss ? 1.02 : 1.05) : 1.035),
      duration: (kind === "enemy" ? 1700 : 1300) + Math.random() * 400,
      yoyo: true,
      repeat: -1,
      ease: "Sine.easeInOut",
    });
  }

  setName(name: string): void {
    this.nameText.setText(name);
  }

  /** Show a worn achievement title beneath the name (players; "" hides). */
  setTitle(title: string): void {
    if (!title) {
      this.titleText?.destroy();
      this.titleText = undefined;
      return;
    }
    if (!this.titleText) {
      this.titleText = this.scene.add
        .text(0, -this.radius - 36, "", {
          fontFamily: "Georgia, serif",
          fontSize: "11px",
          fontStyle: "italic",
          color: "#ffd166",
        })
        .setOrigin(0.5)
        .setStroke("#05070a", 3);
      this.container.add(this.titleText);
    }
    this.titleText.setText(`« ${title} »`);
  }

  /** PvP skull badge (aggressor flag) beside the name. */
  setSkulled(skulled: boolean): void {
    if (!skulled) {
      this.skullBadge?.destroy();
      this.skullBadge = undefined;
      return;
    }
    if (this.skullBadge) return;
    this.skullBadge = this.scene.add
      .text(this.nameText.width / 2 + 10, -this.radius - 24, "☠", {
        fontSize: "13px",
        color: "#ff6b60",
      })
      .setOrigin(0.5)
      .setStroke("#05070a", 3);
    this.container.add(this.skullBadge);
  }

  setHp(hp: number, maxHp: number): void {
    const pct = maxHp > 0 ? Phaser.Math.Clamp(hp / maxHp, 0, 1) : 0;
    this.hpBar.width = BAR_WIDTH * pct;
    this.hpBar.fillColor = pct > 0.5 ? 0x4ade80 : pct > 0.25 ? 0xfacc15 : 0xef4444;
  }

  /** Dim + crumple while dead (downed player / slain mob), with a dust puff. */
  setAlive(alive: boolean): void {
    if (alive === this.alive) return;
    this.alive = alive;
    if (!alive) {
      // A corpse must release its hit area — loot drops right under it, and a
      // still-interactive body eats the pile's clicks until respawn.
      if (this.body.input) this.body.disableInteractive();
      dustPuff(this.scene, this.container.x, this.container.y + 8);
      this.scene.tweens.add({
        targets: this.body,
        angle: this.kind === "enemy" ? 84 : -84,
        duration: 220,
        ease: "Quad.easeIn",
      });
      this.container.setAlpha(0.3);
    } else {
      if (this.body.input) this.body.setInteractive();
      this.body.setAngle(0);
      this.container.setAlpha(1);
    }
  }

  /** Show/hide the elk beneath a mounted rider. */
  setMounted(mounted: boolean): void {
    if (mounted && !this.mount) {
      this.mount = this.scene.add.image(0, 6, "mount-elk");
      this.container.addAt(this.mount, 1); // above shadow, below everything else
      this.body.setY(-14);
    } else if (!mounted && this.mount) {
      this.mount.destroy();
      this.mount = undefined;
      this.body.setY(-4);
    }
  }

  /** Snap to a world position (used on spawn and for the predicted local player). */
  setPosition(x: number, y: number): void {
    this.trackMotion(x, y);
    this.container.setPosition(x, y);
  }

  /** Smoothly move toward a world position (used for remote entity interpolation). */
  lerpTo(x: number, y: number, t: number): void {
    const nx = Phaser.Math.Linear(this.container.x, x, t);
    const ny = Phaser.Math.Linear(this.container.y, y, t);
    this.trackMotion(nx, ny);
    this.container.setPosition(nx, ny);
  }

  /** Facing flip + a walk bob whenever the entity is actually moving. */
  private trackMotion(x: number, y: number): void {
    const dx = x - this.lastX;
    const dy = y - this.lastY;
    this.lastX = x;
    this.lastY = y;
    if (Math.abs(dx) > 0.1) {
      this.body.setFlipX(dx < 0);
      if (this.mount) this.mount.setFlipX(dx < 0);
    }
    if (Math.abs(dx) + Math.abs(dy) > 0.35 && this.alive) {
      this.moving = 6;
    }
    if (this.moving > 0) {
      this.moving -= 1;
      this.bobPhase += this.mount ? 0.55 : 0.38;
      const bob = Math.abs(Math.sin(this.bobPhase)) * (this.mount ? 3.4 : 2.4);
      this.body.setY((this.mount ? -14 : -4) - bob);
      this.shadow.setAlpha(0.8 - bob * 0.06);
      // The two-frame stride: swap legs with the bob rhythm (players only).
      if (this.kind !== "enemy" && !this.mount) {
        const frame = Math.sin(this.bobPhase) >= 0 ? `${this.baseTex}-w1` : `${this.baseTex}-w2`;
        if (this.body.texture.key !== frame) this.body.setTexture(frame);
      }
    } else {
      this.body.setY(this.mount ? -14 : -4);
      this.shadow.setAlpha(0.8);
      if (this.kind !== "enemy" && this.body.texture.key !== this.baseTex) {
        this.body.setTexture(this.baseTex);
      }
    }
  }

  /** Brief white flash when hit. */
  hitFlash(): void {
    this.body.setTintFill(0xffffff);
    this.scene.time.delayedCall(80, () => this.body.clearTint());
  }

  /** Floating "-N" damage number that drifts up and fades. */
  floatingDamage(amount: number): void {
    this.floatingText(`-${amount}`, "#ffd166");
  }

  /** Floating green "+N" heal number. */
  floatingHeal(amount: number): void {
    this.floatingText(`+${amount}`, "#4ade80");
  }

  /** Gray "Miss" — a swing that didn't land is still feedback. */
  floatingMiss(): void {
    this.floatingText("Miss", "#9aa4b5");
  }

  private floatingText(label: string, color: string): void {
    const text = this.scene.add
      .text(this.container.x, this.container.y - this.radius - 24, label, {
        fontFamily: "system-ui, sans-serif",
        fontSize: "16px",
        color,
        fontStyle: "bold",
      })
      .setOrigin(0.5)
      .setStroke("#05070a", 4)
      .setDepth(20);
    this.scene.tweens.add({
      targets: text,
      y: text.y - 32,
      alpha: 0,
      duration: 600,
      ease: "Cubic.easeOut",
      onComplete: () => text.destroy(),
    });
  }

  destroy(): void {
    this.container.destroy();
  }
}
